### ISSUE TITLE
'npm test' gives error related to FsProvider

### ISSUE THREAD

**Issue by DzyubSpirit** [metarhia/globalstorage#115]
Error: Can not open database: ./data
    at readStat (/home/dzyubspirit/programs/metarhia/globalstorage/lib/fs.provider.js:46:18)
    at ReadFileContext.fs.readFile [as callback] (/home/dzyubspirit/programs/metarhia/globalstorage/lib/fs.provider.js:27:7)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:334:13)
/home/dzyubspirit/programs/metarhia/globalstorage/node_modules/mongodb/lib/mongo_client.js:792
          throw err;

TypeError: Cannot read property 'db' of null
    at mongodb.connect (/home/dzyubspirit/programs/metarhia/globalstorage/test/mongodb.js:40:21)
    at err (/home/dzyubspirit/programs/metarhia/globalstorage/node_modules/mongodb/lib/utils.js:415:14)
    at executeCallback (/home/dzyubspirit/programs/metarhia/globalstorage/node_modules/mongodb/lib/utils.js:404:25)
    at /home/dzyubspirit/programs/metarhia/globalstorage/node_modules/mongodb/lib/mongo_client.js:269:21
    at connectCallback (/home/dzyubspirit/programs/metarhia/globalstorage/node_modules/mongodb/lib/mongo_client.js:944:5)
    at /home/dzyubspirit/programs/metarhia/globalstorage/node_modules/mongodb/lib/mongo_client.js:789:11
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by tshemsedinov** [comment]
Here are two different errors
- first one related to `FsProvider` see last CI build: https://travis-ci.org/metarhia/globalstorage/jobs/370857938 and can be fixed by creating needed directory structure (not added to repo)
- second one related to mongodb connection, maybe you have no started mongodb server

**Comment by tshemsedinov** [comment]
Everything works fine after:
- update `mongodb` driver to 3.0.8
- add `/data/.gs` to the repo
