### ISSUE TITLE
'node test/fs.js' gives error

### ISSUE THREAD

**Issue by DzyubSpirit** [metarhia/globalstorage#117]
fs.js test works only after requiring mongodb.js test. Is it okay? I ask because unit tests should be independent. These are unit tests, aren't they?
'node test/fs.js' gives:
```
Select test: 
[ Error: Not implemented
    at FsCursor.Cursor.fetch (/home/dzyubspirit/programs/metarhia/globalstorage/lib/cursor.js:296:8)
    at gs.open (/home/dzyubspirit/programs/metarhia/globalstorage/test/fs.js:36:6)
    at wrap (/home/dzyubspirit/programs/metarhia/globalstorage/node_modules/metarhia-common/lib/callbacks.js:46:5)
    at readStat (/home/dzyubspirit/programs/metarhia/globalstorage/lib/fs.provider.js:47:9)
    at fs.readFile (/home/dzyubspirit/programs/metarhia/globalstorage/lib/fs.provider.js:34:5)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:422:3),
  undefined ]
```

**Comment by tshemsedinov** [comment]
That's because `FsCursor` isn't implemented, `test/fs.js` should not work, but it works because `gs` is already opened from previous test and uses `MongodbCursor` instead.
